[package]
name = "cincinnati"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]

[dependencies]
daggy = { version = "^0.6.0", features = [ "serde-1" ] }
failure = "^0.1.1"
serde = "1.0.70"
serde_derive = "1.0.70"
commons = { path = "../commons" }
quay = { path = "../quay" }
protobuf = "2.0"
url = "^1.7.2"
log = "^0.4.3"
futures = "0.1"
futures-locks = "0.3.3"
tokio = "0.1"
toml = "^0.4.10"
env_logger = "^0.6.0"
lazy_static = "^1.2.0"
regex = "^1.1.0"
smart-default = "^0.5.2"
hyper = "^0.12.6"
actix-web = "^1.0.2"
serde_json = "^1.0.22"
prometheus = "^0.7.0"
custom_debug_derive = "^0.1.7"

[dev-dependencies]
serde_json = "1.0.22"
mockito = "^0.17.1"

[build-dependencies]
protoc-rust = "2.0"

[features]
codegen-protoc = []
test-net = []
test-net-private = []
