[package]
name = "policy-engine"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]
edition = "2018"

[dependencies]
actix = "^0.8.3"
actix-web = "^1.0.2"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
env_logger = "^0.6.0"
failure = "^0.1.1"
futures = "^0.1.23"
hyper = "^0.12.6"
lazy_static = "^1.2.0"
log = "^0.4.3"
openapiv3 = "0.1"
prometheus = "^0.7.0"
semver = "^0.9.0"
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
smart-default = "^0.5.1"
structopt = "^0.2.10"
toml = "^0.4.10"
url = "1.7.2"
tempfile = "^3.1.0"
custom_debug_derive = "^0.1.7"

[dev-dependencies]
tokio = "^0.1"
twoway = "^0.2"
mockito = "^0.17.1"
